application: elite-clover-821
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /dialog-polyfill
  static_dir: bower_components/dialog-polyfill

- url: /build
  static_dir: live-editor/build

- url: /js
  static_dir: build

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
